add kas project configuration
bisdn/bisdn-linux pull request #98
Opened 2023-11-24 11:30 UTC by KanjiMonster

Add a kas project configuration for bisdn-linux and additional snippets for building OF-DPA from source or doing nightly/release builds.

In contrast to repo the initial checkout must be done manually, but also kas will configure the build and add any layers automatically.

So the minimal steps for building bisdn-linux via kas are:

```
$ git clone https://github.com/bisdn/bisdn-linux.git
$ cd bisdn-linux/
$ kas checkout bisdn-linux.yml
$ kas build bisdn-linux.yml
```

The checkout is slightly faster:

```
$ time kas checkout bisdn-linux.yml:ofdpa-gitlab.yml
...
real	0m14,519s
user	0m35,906s
sys	0m5,031s
```

```
$ repo init -g all,ofdpa-gitlab -u https://github.com/bisdn/bisdn-linux.git
$ time repo sync
...
real	2m14,857s
user	0m50,205s
sys	0m6,116s
```

2024-09-27 13:19 UTC, KanjiMonster commented
Recent changes:
* .yml => .yaml - this isn't 1995 anymore, we can have extensions with more than 3 characters
* removed the change of targets since I noticed that what is needed to work for that correctly cannot be expressed by kas configuration
* dropped nightly.yaml, since when removing the extra target it becomes empty
* reduced release.yaml to just the changed feed location, anything else isn't needed to building a release image
* updated the README.md to also describe how to build with kas(-container)

2024-10-01 11:57 UTC, KanjiMonster commented
Dropped the readme changes for now.

2024-10-01 12:32 UTC, jklare requested changes
LGTM, one minor comment

2024-10-01 12:39 UTC, KanjiMonster commented on scripts/convert.sh
> -	VERSION=$(cat ${TOPDIR}/bisdn-linux.yml | yq -r '.header.version')
Ah, oops, yes. Let me fix it.

2024-10-01 12:41 UTC, KanjiMonster commented on scripts/convert.sh
> -	VERSION=$(cat ${TOPDIR}/bisdn-linux.yml | yq -r '.header.version')
Fixed.

2024-10-01 15:48 UTC, jklare approved these changes
lgtm

2024-10-01 15:48 UTC, merged